import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'
import { registerSW } from 'virtual:pwa-register'

// Register the service worker generated by vite-plugin-pwa.
// updateSW is called automatically when a new version is detected (autoUpdate).
registerSW({
  onNeedRefresh() {
    // New content available — the plugin handles the reload automatically
    // because registerType is 'autoUpdate'.
  },
  onOfflineReady() {
    console.log('App is ready to work offline.')
  },
})

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
